version: "3.8"
services:
  
  perlt-bank:
    image: "perlt/perlt-bank"
    restart: unless-stopped

  bank-proxy:
    image: "perlt/bank-proxy"
    restart: unless-stopped
  
  login-module:
    image: "perlt/login-module"
    restart: unless-stopped

  esb:
    image: "perlt/esb"
    ports:
      - 8080:8080
    restart: unless-stopped

  rabbitmq:
    image: "rabbitmq:3-management"
    restart: unless-stopped
  
  mongo:
    image: "mongo"
    restart: unless-stopped


# emailModule hosted on https://emailmodule20201203224626.azurewebsites.net/
