
package com.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExchangeServiceSoapPort", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExchangeServiceSoapPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.baeldung.soap.ws.client.generated.DkToUsdOutput
     */
    @WebMethod(operationName = "DkToUs", action = "DkToUs")
    @WebResult(name = "DkToUsdOutput", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public DkToUsdOutput dkToUs(
        @WebParam(name = "DkToUsdInput", targetNamespace = "http://tempuri.org/", partName = "parameters")
        DkToUsdInput parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.baeldung.soap.ws.client.generated.UsdToDkOutput
     */
    @WebMethod(operationName = "UsToDk", action = "UsToDk")
    @WebResult(name = "UsdToDkOutput", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public UsdToDkOutput usToDk(
        @WebParam(name = "UsdToDkInput", targetNamespace = "http://tempuri.org/", partName = "parameters")
        UsdToDkInput parameters);

}
